# Generated by Django 4.2.4 on 2023-09-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_cart_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
